
orix_chunck_malloc_address_small_low:
	.byt <chunk_small
    .byt <chunk_small+ORIX_CHUNK_MALLOC_SIZE_SMALL
orix_chunck_malloc_address_small_high:
    .byt >chunk_small
    .byt >chunk_small+ORIX_CHUNK_MALLOC_SIZE_SMALL

orix_chunck_malloc_address_big_low:
    .byt <chunk_big
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*2
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*3
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*4
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*5
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*6
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*7
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*8
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*9
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*10
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*11
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*12
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*13
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*14
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*15
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*16
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*17
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*18
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*19
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*20
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*21
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*22
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*23
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*24
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*25
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*26
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*27
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*28
    .byt <chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*29
orix_chunck_malloc_address_big_high:
    .byt >chunk_big
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*2
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*3
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*4
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*5
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*6
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*7
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*8
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*9
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*10
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*11
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*12
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*13
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*14
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*15
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*16
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*17
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*18
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*19
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*20
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*21
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*22
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*23
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*24
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*25
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*26
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*27
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*28
    .byt >chunk_big+ORIX_CHUNK_MALLOC_SIZE_BIG*29
